/// <reference lib="webworker" />
/* eslint-disable no-restricted-globals */

import { clientsClaim } from 'workbox-core';
import { precacheAndRoute, createHandlerBoundToURL } from 'workbox-precaching';
import { NavigationRoute, registerRoute } from 'workbox-routing';

declare let self: ServiceWorkerGlobalScope & { __WB_MANIFEST: any };

clientsClaim();

// Precache all of the assets generated by the build process.
precacheAndRoute(self.__WB_MANIFEST);

// App Shell-style routing, so that all navigation requests
// are fulfilled with index.html shell.
const appShellHandler = createHandlerBoundToURL(`${process.env.PUBLIC_URL || ''}/index.html`);
registerRoute(
  new NavigationRoute(appShellHandler, {
    denylist: [new RegExp('^/_'), new RegExp('/[^/?]+\.[^/]+$')],
  })
);

self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});
